workflows:
  ios-workflow:
    name: iOS Workflow - Expense Tracker Nepal
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app (no signing)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/Runner.xcarchive
    publishing:
      email:
        recipients:
          - abhishekhkapar@gmail.com
        notify:
          success: true
          failure: true
